apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "poundcake.fullname" . }}-mappings
  labels:
    {{- include "poundcake.labels" . | nindent 4 }}
data:
  {{- range $filename, $content := .Values.mappings }}
  {{ $filename }}: |
    {{- $content | nindent 4 }}
  {{- end }}
