{{- if and .Values.redis.enabled .Values.redis.deploy .Values.redis.password (not .Values.redis.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "poundcake.fullname" . }}-redis
  labels:
    {{- include "poundcake.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
type: Opaque
data:
  {{ .Values.redis.secretKey }}: {{ .Values.redis.password | b64enc | quote }}
{{- end }}
