{{- if and (not .Values.stackstorm.existingSecret) (or .Values.stackstorm.apiKey .Values.stackstorm.authToken) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "poundcake.fullname" . }}-stackstorm
  labels:
    {{- include "poundcake.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.stackstorm.apiKey }}
  {{ .Values.stackstorm.secretKeys.apiKey }}: {{ .Values.stackstorm.apiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.stackstorm.authToken }}
  {{ .Values.stackstorm.secretKeys.authToken }}: {{ .Values.stackstorm.authToken | b64enc | quote }}
  {{- end }}
{{- end }}
