{{- if and (not .Values.stackstorm.existingSecret) (or .Values.stackstorm.apiKey .Values.stackstorm.authToken) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "poundcake.fullname" . }}-stackstorm
  labels:
    {{- include "poundcake.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.stackstorm.apiKey }}
  {{ .Values.stackstorm.secretKeys.apiKey }}: {{ .Values.stackstorm.apiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.stackstorm.authToken }}
  {{ .Values.stackstorm.secretKeys.authToken }}: {{ .Values.stackstorm.authToken | b64enc | quote }}
  {{- end }}
{{- end }}
---
{{- if .Values.auth.enabled }}
{{- $secretName := printf "%s-admin" (include "poundcake.fullname" .) }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- $adminPassword := "" }}
{{- if $existingSecret }}
  {{- $adminPassword = index $existingSecret.data "password" | b64dec }}
{{- else }}
  {{- $adminPassword = randAlphaNum 24 }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "poundcake.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  username: {{ "admin" | b64enc | quote }}
  password: {{ $adminPassword | b64enc | quote }}
{{- end }}
