apiVersion: v2
name: poundcake
description: Auto-remediation framework bridging Prometheus Alertmanager with StackStorm
type: application
version: 0.2.2
appVersion: "0.2.7"
maintainers:
  - name: Jake Briggs
keywords:
  - alertmanager
  - stackstorm
  - auto-remediation
  - prometheus
  - automation
home: https://github.com/aedan/poundCake
sources:
  - https://github.com/aedan/poundCake
