apiVersion: v2
name: poundcake
description: Auto-remediation framework bridging Prometheus Alertmanager with StackStorm
type: application
version: 0.1.5
appVersion: "0.1.5"
maintainers:
  - name: Jake Briggs
keywords:
  - alertmanager
  - stackstorm
  - auto-remediation
  - prometheus
  - automation
home: https://github.com/aedan/poundCake
sources:
  - https://github.com/aedan/poundCake
